# Generated by Django 5.2.4 on 2026-07-12 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="employee",
            managers=[],
        ),
    ]
