# Generated by Django 5.2.4 on 2026-07-12 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_employee_managers"),
    ]

    operations = [
        migrations.AddField(
            model_name="department",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
