# Generated by Django 5.2.16 on 2026-07-12 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audits", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditrecord",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
    ]
